spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource  # Configuración específica de Tomcat JDBC

  security:
     user.password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Actualización de la clave de configuración
    defer-datasource-initialization: true
